"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[[blocks]]
alignment = "left"
type = "prompt"
newline = true
  [[blocks.segments]]
  foreground = "#88c0d0"
  style = "plain"
  template = "<#5e81ac>┏[</>{{ .UserName }}<#5e81ac>]</>"
  type = "session"

  [[blocks.segments]]
  foreground = "#b48ead"
  style = "plain"
  template = "<#5e81ac>--[</>{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}<#8fbcbb> ● </>{{ end }}{{ if .Staging.Changed }}<#88c0d0> ● </>{{ end }}<#5e81ac>]</>"
  type = "git"

    [blocks.segments.properties]
    fetch_stash_count = true
    fetch_status = true
    fetch_upstream_icon = true

  [[blocks.segments]]
  foreground = "#b48ead"
  style = "plain"
  template = "<#5e81ac>--[</>{{.Profile}}{{if .Region}}@{{.Region}}{{end}}<#5e81ac>]</>"
  type = "aws"

  [[blocks.segments]]
  foreground = "#b48ead"
  style = "plain"
  template = "<#5e81ac>--[</>{{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}<#5e81ac>]</>"
  type = "kubectl"

  [[blocks.segments]]
  foreground = "#d8dee9"
  style = "plain"
  template = "<#5e81ac>[</><#5e81ac>]</>"
  type = "root"

  [[blocks.segments]]
  foreground = "#d8dee9"
  style = "plain"
  template = "<#5e81ac>[x</>{{ reason .Code }}<#5e81ac>]</>"
  type = "status"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#88c0d0"
  style = "plain"
  template = "<#5e81ac>┖[</>{{ .Path }}<#5e81ac>]</>"
  type = "path"

    [blocks.segments.properties]
    style = "full"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#5e81ac"
  style = "plain"
  template = "  "
  type = "text"

[transient_prompt]
  template = "  "
  foreground = "#5e81ac"
  background = "transparent"
