[aws]
disabled = true

[directory]
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "

#[character]
#success_symbol = '[➜](bold green) '
#error_symbol = '[✗](bold red) '
