[general]
import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal.family = "CodeNewRoman Nerd Font Mono"
size = 13

[window]
padding.x = 5
padding.y = 5

opacity = 0.6
blur = true

[mouse]
hide_when_typing = true
